### ISSUE TITLE
get/set current directory is not consistent on Mac Big Sur

### ISSUE THREAD

**Issue by yaitskov** [haskell/directory#128]
Hi,

```
$ stack ghci --package directory
> import System.Directory
> setCurrentDirectory "/tmp"
> getCurrentDirectory 
"/private/tmp"
```

**Comment by Rufflewind** [comment]
`getCurrentDirectory` calls the POSIX [`getcwd`](https://pubs.opengroup.org/onlinepubs/007904975/functions/getcwd.html) API. The POSIX spec stipulates that `getcwd` cannot return a path containing symbolic links, so if you `setCurrentDirectory` to a path containing symbolic links (`/tmp`) it will be dereferenced to the underlying path (`/private/tmp`).

**Comment by yaitskov** [comment]
Doh! This is super counter intuitive. I wish to know the reason why symlink is not acceptable. If POSIX is screwed then Haskell should outline that through type system e.g.


```
getCurrentDirectory :: IO CanonicalPath
setCurrentDirectory :: SymDotsPath -> IO ()
```

**Comment by Rufflewind** [comment]
> I wish to know the reason why symlink is not acceptable.

I can't speak for why POSIX is the way it is, but generally speaking the "current working directory" as held by a process is really a handle to the underlying directory object (inode), rather than the path to the directory. For example, if you rename the current directory while the process is still running, then `getcwd` would automatically return the new path. Some programs will track the path separately in memory for convenience (e.g. Bash), but that is not a native feature of the operating system.

I don't really think it's feasible to represent this in the type system. Whether a path is canonical is not an immutable fact.

It may be beneficial to clarify this behavior in the documentation, nonetheless.
