### ISSUE TITLE
Feature request: createLink

### ISSUE THREAD

**Issue by chris-martin** [haskell/directory#154]
Would it be feasible to add a generic `createLink :: OsPath -> OsPath -> IO ()` function which would...

- On Posix, create a link
- On Windows, determine whether the link target is a file or a directory and then perform either `createFileLink` or `createDirectoryLink` as appropriate

**Comment by Rufflewind** [comment]
I think it was precisely because of the edge case on Windows that the API was split into createFileLink and createDirectoryLink. The link itself retains the directory-vs-file bit on Windows, even if the destination changes from file to directory or vice versa.

Merging them into one API is in principle possible, but it can result in confusing expectations from users, so I would rather not have such an API that mixes the two.

Thank you for filing the issue. I think this would be better suited for a higher-level library.
