### ISSUE TITLE
createDirectoryIfMissing does not fail on unwritable parent dir

### ISSUE THREAD

**Issue by ekmett** [haskell/directory#22]
On OSX, using createDirectoryIfMissing to create a new directory inside a directory for which we do not have write permissions does not throw any exception. Of course it should throw an exception, as it does under Linux.

```
$ mkdir unwritable
$ chmod ugo-w unwritable
$ ghci
> System.Directory.createDirectoryIfMissing True "unwritable/tst"
>
```

On OSX (10.9.2) this does not fail. Under Linux (albeit with 7.6.3) this does throw an exception as expected:

```
*** Exception: unwritable/tst: createDirectory: permission denied (Permission denied)
```

Original Trac Ticket: https://ghc.haskell.org/trac/ghc/ticket/9044

**Comment by Rufflewind** [comment]
Reproducible on BSD as well.

**Comment by Rufflewind** [comment]
The bug is reproducible on BSD and, oddly, Linux as well.  However it seems to only affect 1.2.1.0, not HEAD.  I think it's related to [#4](https://github.com/haskell/directory/issues/22) and has been fixed by [1f1139](https://github.com/haskell/directory/commit/1f113935439a381443b945eb5177fb122881f182).  Just to make sure, I asked two Mac users to reproduce this with HEAD and it appears to be no longer an issue.
