### ISSUE TITLE
@since not rendered properly on Hackage

### ISSUE THREAD

**Issue by kraai** [haskell/directory#37]
The @since tags don't appear to be rendered properly on Hackage.  I think that the should be shown as "Since: 1.2.3.0", in italics, since that's what's done for modules such as System.Process.  Instead, they're shown as "@since 1.2.3.0", using a regular font.

**Comment by Rufflewind** [comment]
`@since` was added in a recent version of Haddock.  Unfortunately Hackage is still running on an old version of Haddock, so only thing we can do is to wait until they deploy the new version.  If the need is urgent, consider submitting a bug report on [Hackage server](https://github.com/haskell/hackage-server).

**Comment by kraai** [comment]
@Rufflewind Thanks for the information, but I don't see how the @since tags in the System.Process documentation are rendered correctly, then.  Here's an example:

https://hackage.haskell.org/package/process-1.3.0.0/docs/System-Process.html#v:createProcess_

**Comment by Rufflewind** [comment]
> Status: Docs uploaded by user

Their documentation was uploaded manually.

**Comment by kraai** [comment]
Ohhh.  Thanks for the explanation!
