### ISSUE TITLE
Behavior of `getHomeDirectory` and/or `canonicalizePath` is inconsistent across GHC versions 

### ISSUE THREAD

**Issue by mrkkrp** [haskell/directory#44]
Here is the test:

https://github.com/mrkkrp/path-io/blob/master/tests/Main.hs#L116

It succeds with 7.10, but fails with 7.8 and 8.0:

https://travis-ci.org/mrkkrp/path-io/jobs/110565920#L381

At first I decided to “forgive” 7.8 and added some CPP to skip that test there, but now I added 8.0 to build matcix and this thing again throws something unexpected. `getHomeDir` uses `getHomeDirectory` and `canonicalizePath`, so the only thing it can throw in the setting of that test is `isDoesNotExistError`. Any comment?

**Comment by Rufflewind** [comment]
[`canonicalizePath` used to have unpredictable behavior* on non-existent paths](https://github.com/haskell/directory/issues/23) in versions of directory older than 1.2.3.0.  Since 1.2.3.0, it was fixed to return a sensible result for any path, even non-existent ones.  Hence, your test should expect no errors at all, but only if directory is 1.2.3.0 or newer.  Otherwise, all bets are off.

Keep in mind that the version of `directory` is not tied to that of GHC or `base`.  Consider checking for `directory`'s version rather than `base`:

~~~cpp
#if MIN_VERSION_directory(1, 2, 3)
~~~

Your Travis tests for [GHC 7.8 pulled in directory-1.2.5.0](https://travis-ci.org/mrkkrp/path-io/jobs/110107991#L297), but for [GHC 7.10 it was using directory-1.2.2.0](https://travis-ci.org/mrkkrp/path-io/jobs/110107994#L291).

**Comment by mrkkrp** [comment]
Thanks for the explanation, I will update the tests accordingly.
