### ISSUE TITLE
Add ability to get file/folder properties

### ISSUE THREAD

**Issue by noughtmare** [haskell/directory#57]
Is it possible to add a function like:

    getProperties :: FilePath -> IO Properties
    
    data Properties = Properties {
      name :: String
      type :: String
      size :: Integer
      etc...
    }

Thank you!

**Comment by Rufflewind** [comment]
- `name`: [Basename of the file](https://hackage.haskell.org/package/filepath-1.4.1.0/docs/System-FilePath-Posix.html#v:takeFileName)?
- `type`: What do you mean by type of a file? Mind giving some examples?
- `size`: This is useful.  I was not able to find another library that does this portably.
- `etc`: Would you mind clarifying which properties you are interested in?

**Comment by noughtmare** [comment]
Sorry, I was being way to vague and general.

For my current project I really only need a function that gets the mime type of a file (i.e. image/jpeg) and a function that checks if a filepath is a directory:

    getMIMEType :: FilePath -> IO String
    isDirectory :: FilePath -> IO Bool

**Comment by Rufflewind** [comment]
Since MIME types are not stored as part of the files themselves, there is no accurate way to determine the MIME type without applying a tedious set of heuristic algorithms on the contents of the files. Unfortunately, this means it does not lie within the scope of `directory`.  Consider using the `magic` library instead.

`isDirectory` might be a useful addition.  Currently, there is `doesDirectoryExist`, which doesn't quite do the same thing but suffices for many albeit not all purposes.

**Comment by Rufflewind** [comment]
So I went ahead and implemented the following:

  - `getFileSize`
  - `doesPathExist`

I was originally going to implement `isDirectory`, but I felt that adding `doesPathExist` is more useful, since it can be used to implement both `isDirectory` and `isFile`, while also avoiding naming conflicts with `unix`.

One could then implement `isDirectory` like this:
~~~hs
isDirectory :: FilePath -> IO Bool
isDirectory path = do
  exists <- doesPathExist path
  if exists
    then doesDirectoryExist path
    else ioError (mkIOError doesNotExistErrorType "isDirectory" Nothing (Just path))
~~~
