### ISSUE TITLE
removeDirectoryRecursive: permission denied (Access is denied.) Windows

### ISSUE THREAD

**Issue by wapxmas** [haskell/directory#59]
Please read this [issue](https://github.com/commercialhaskell/stack/issues/2426). Thanks.

**Comment by Blaisorblade** [comment]
Thanks for your investigation on the original issue (got here from stack)!

To summarize (correct me if I'm wrong): `removeFile ` hence `removeDirectoryRecursive` can't remove read-only files, even when it is possible by first clearing the read-only flag. Do you propose indeed clearing the read-only flag? That would certainly be consistent with the behavior on Unix.

https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa363915(v=vs.85).aspx

**Comment by wapxmas** [comment]
Yes, I think that clearing read-only flag when it is possible it is right behavior. I think if I want to delete file or directory recursive I don`t really care read-only file or not. Thanks.

**Comment by Rufflewind** [comment]
> That would certainly be consistent with the behavior on Unix.

*nix and Windows behave differently in that on *nix the permission to delete is determined by the write-bit on the parent directory, whereas on Windows the permission to delete is determined by the attributes of the file itself.  I don't believe there's a way to make this "consistent" without doing a lot of ugly hacks.

---

I agree that the failure to delete read-only files is kind of annoying and probably not what the user expects.

However, I'm somewhat hesitant on changing the behavior of a core function such as `removeFile`.  Moreover, it is currently consistent with the behavior in Python's standard library.

I could add something like `removeFileForcibly` though, or maybe a helper function like `setWritablePermission :: Bool -> FilePath -> IO ()`.

**Comment by Blaisorblade** [comment]
I agree a bit with your hesitation; I'd propose to add mention of this issue then for `removeFile` together with any addition.

Would you be open to changing `removeDirectoryRecursive` to use `removeFileForcibly` though, or adding a variant for that?
For the original linked issue on Stack, I think we would want a portable `rm -rf` which does remove readonly files.

I suppose that at least any build tool removing directories it created (cabal-install, Shake, ...) would need the same behavior, so I think this would be useful in a common package rather than inside Stack.

Since you mention the Python standard library, I found its [shutil.rmtree](https://docs.python.org/3.5/library/shutil.html#shutil.rmtree) function: they provide a callback for handling errors on a single deletion, which could be used to change permissions and allow to resume operations.

**Comment by Rufflewind** [comment]
I've added `removePathForcibly`, which can remove files or directories even if they are read-only or non-existent.
