### ISSUE TITLE
Properly support XDG Base Directory Specification

### ISSUE THREAD

**Issue by hvr** [haskell/directory#6]
`directory` provides a function `getAppUserDataDirectory :: String -> IO FilePath` which on Linux simply constructs the resulting path as `${HOME}/.${APPNAME}`.

However, that doesn't conform to the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Further reading:

 - http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
 - https://wiki.debian.org/XDGBaseDirectorySpecification
 - https://wiki.gnome.org/Initiatives/GnomeGoals/XDGConfigFolders

**Comment by Rufflewind** [comment]
> If we have to deprecate the current `getAppUserDataDirectory` function incarnation each time we discover the need to update the scheme to conform to some new OS-specific convention, we'll end up with several such functions.

I don't think new OS conventions would appear so rapidly as to be a problem.  I also don't think there's a way to implement this in a backward-compatible manner: changing the location will cause surprises for both developers and end-users downstream.

If we do add a new function, `getAppUserDataDirectory` should *not* be deprecated, since some may prefer the traditional behavior.  From my experience, quite a few programs (probably the majority) still use the traditional location.

We could add the following functions:

  - `getXdgUserDataDirectory`: `XDG_DATA_HOME` (`~/.local/share`); Windows: `AppData/Roaming`?
  - `getXdgUserConfigDirectory`: `XDG_CONFIG_HOME` (`~/.config`); Windows: `AppData/Roaming`
  - `getXdgUserCacheDirectory`: `XDG_CACHE_HOME` (`~/.cache`); Windows: `AppData/Local`
  - `getXdgUserRuntimeDirectory`: `XDG_RUNTIME_DIR` (`/tmp/<user>/<app>`?); Windows: `AppData/Local/Temp`?

and perhaps some utility functions for obtaining various search paths:

  - `getExecutableDirectories`: `PATH` (not relevant to this issue though)
  - `getXdgDataDirectories`: `XDG_DATA_DIRS` (`/usr/local/share/:/usr/share`); Windows: none?
  - `getXdgConfigDirectories`: `XDG_CONFIG_DIRS` (`/etc/xdg`); Windows: none?

However, I don't know if we should add all of them right away since not all of them are necessarily in demand.  (Do people even use `XDG_RUNTIME_DIR`?  Using `/etc/xdg` seems very unnecessary, IMO.)

**Comment by Rufflewind** [comment]
Fixed in https://github.com/haskell/directory/commit/ab9d0810ce0172e10ff1ca437ad7f723d6648f0d

(I did not implement the utility functions nor `XDG_RUNTIME_DIR` however.  Nonetheless, if anyone else has a need for them feel free to open another ticket.)

**Comment by hvr** [comment]
@Rufflewind I'm wondering, with the given operation, what's the recommended upgrade path for code currently using `getAppUserDataDirectory`? If we have a recommendation, which may want to document it in the Haddocks...

**Comment by Rufflewind** [comment]
The upgrade path is not straightforward unfortunately:

  - For one thing, using the new location will obviously break the existing configuration, so a well-behaved application will need to seamlessly migrate the files to the new location.  (And update documentation, tutorials, etc.)

  - Secondly, there's the question of *where* the files are to be migrated: depending on how strict the application wants to follow the XDG specs, it will have to decide whether the files are moved to `~/.local/share`, `~/.config`, `~/.cache`, or some subset of those.  I think if the developer wants to be lazy and not think about it, `~/.config` seems like a good bet.  Chromium, for example, just dumps *everything* into `~/.config`.

Now, changing the relevant code to use XDG isn't that difficult:

    getAppUserDataDirectory "myapp"

may be replaced with

    (</> "myapp") <$> getXdgDirectory XdgConfig

(Substitute `XdgConfig` with `XdgData` or `XdgCache` as needed.)

I can add some of this to the docs but ultimately the hardest part is doing the migration :/

**Comment by hvr** [comment]
**bikeshed-warning** Looking at your last example, I wonder if there are any cases where you want the base-folder returned by 

    getXdgDirectory :: XdgDirectory -> IO FilePath

rather than having the slightly more convenient form

    getXdgDirectory :: XdgDirectory -> FilePath -> IO FilePath

which would encode the policy that you're expected to refer to an app-specific subfolder in the respective Xdg-base-folder... (and if you deliberately pass the empty string or `"."`, you'd still get the base-folder)

**Comment by Rufflewind** [comment]
I agree the latter is more convenient.  I picked the former because it felt simpler and didn't make any assumptions as to what the user intended to do with it.

However, I think passing an empty string to get the base directory is reasonable as long as it's documented behavior.  For `getAppUserDataDirectory` it's currently unspecified, but that can be fixed.
