### ISSUE TITLE
`findFile` edges case with absolute paths on Windows

### ISSUE THREAD

**Issue by jmitchell** [haskell/directory#72]
The examples below where `findFile` returns `Nothing` are surprising, and if possible I think they should return the obvious path.

```
Prelude> import System.Directory
Prelude System.Directory> doesFileExist "C:\\tmp\\Test.hs"
True
Prelude System.Directory> findFile [] "C:\\tmp\\Test.hs"
Nothing
Prelude System.Directory> findFile ["C:\\"] "tmp\\Test.hs"
Just "C:\\tmp\\Test.hs"
Prelude System.Directory> findFile [] "\\tmp\\Test.hs"
Nothing
Prelude System.Directory> findFile ["\\"] "tmp\\Test.hs"
Just "\\tmp\\Test.hs"
Prelude System.Directory> setCurrentDirectory "C:\\tmp"
Prelude System.Directory> findFile ["."] "Test.hs"
Just ".\\Test.hs"
```

**Comment by Rufflewind** [comment]
What do you consider the correct behavior to be?  The documentation is rather underspecified currently.

I double-checked the results on my Linux system and there is at least one inconsistency between platforms that needs to be remedied:

    findFile [] "C:\\tmp\\Test.hs"    -- consistent with Linux
    findFile ["C:\\"] "tmp\\Test.hs"  -- (!) succeeds on Linux
    findFile [] "\\tmp\\Test.hs"      -- no Linux equivalent
    findFile ["\\"] "tmp\\Test.hs"    -- no Linux equivalent
    findFile ["."] "Test.hs"          -- consistent with Linux

**Comment by jmitchell** [comment]
**Proposed invariant:** If `doesFileExist fname` returns `True`, I expect `findFile [] fname` to return `Just fname`. The invariant makes sense regardless of platform.

Currently these two cases from above violate the proposed invariant on Windows.

```
Prelude System.Directory> findFile [] "C:\\tmp\\Test.hs"
Nothing
Prelude System.Directory> findFile [] "\\tmp\\Test.hs"
Nothing
```

I expect the first to return `Just "C:\\tmp\\Test.hs"` and the second to return `Just "\\tmp\\Test.hs"`.

**Comment by jmitchell** [comment]
@Rufflewind, do you mind showing the ghci output on Linux corresponding to `findFile ["C:\\"] "tmp\\Test.hs"  -- (!) succeeds on Linux` along with `doesFileExist "C:\\tmp\\Test.hs"`?

**Comment by jmitchell** [comment]
The slash type is significant in Linux (tested on Ubuntu 16.04). May be affecting the results you're seeing.

```
Prelude System.Directory> doesFileExist "tmp\\Test.hs"
False
Prelude System.Directory> doesFileExist "tmp/Test.hs"
True
```

In any case, I recommend the same invariant.

**Comment by Rufflewind** [comment]
> findFile ["/home/rf"] "downloads/somefile.pdf"
    Just "/home/rf/downloads/somefile.pdf"

**Comment by jmitchell** [comment]
Have you found any cases that violate the invariant?

**Comment by Rufflewind** [comment]
Oh, sorry, it seems I have misread.  I thought there was a discrepancy between Windows and Linux, but that was a mistake on my part.

---

It seems the behavior that you are proposing concerns solely with regard to cases where the first argument is `[]`.   There are two possibilities:

  - The given filename is absolute, in which case `findFile` appears to be almost equivalent to `doesFileExist`, except it fails if the first argument is `[]`.
  - The given filename is relative, in which case if there are no directories to begin with, it fails since there are no directories to consult.

I feel like the first behavior may have been accidental and not part of the original API: it only worked because `</>` disregards the first path when the second path is absolute.  It would be wrong to revert that now, but it seems a lot of people have implicitly assumed that `findFile` always worked for absolute paths even though it was accidental (and unnecessarily inefficient, since it still has to go through every directory even if the path is absolute and nonexistent).

In isolation, the first behavior is quite absurd, so I think a compromise would be:

~~~hs
isAbsolute p ==> findFile [] p == if doesFileExist p then Just p else Nothing
~~~

This should minimize the effect on most code except those that rely on `findFile` to handle absolute paths.

- [ ] Tweak behavior to handle absolute paths explicitly.
- [ ] Document the new behavior.
