### ISSUE TITLE
doesDirectoryExist "" changed behaviour

### ISSUE THREAD

**Issue by dbdbdb** [haskell/directory#84]
doesDirectoryExist for the empty string has changed behaviour and now say yes. I have some old code that stopped working when updating this lib.

Couldn't see it documented so I guess it is a bug?

**Comment by hvr** [comment]
A quick bisecting over releases revelead this change occured between `directory-1.3.1.0` (returns `False`) and `directory-1.3.1.1` (returns `True`)

**Comment by dbdbdb** [comment]
I've never seen that semantic in any other language so it would come as a surprise for most I guess.

For example these languages return False for "" and True for ".":

Bash:  [ -d "" ]
Python: os.path.isdir("")
PHP: is_dir("")
Perl: -d ""
Ruby: File.directory?("")
C/C++: stat("", &s) followed by S_ISDIR(s.st_mode) (for empty string stat() return ENOENT)
Java: file = new File("") followed by file.isDirectory()

So it should at least be clearly documented.

**Comment by Rufflewind** [comment]
Okay, upon further thought, I decided to revert the change, mainly because operating systems do not treat `""` and `"."` as the same.  For example, `setCurrentDirectory ""` fails and I think it's better to leave it that way.

It's unfortunate that some of the existing API (i.e. `canonicalizePath`, `makeAbsolute`, timestamps, and permissions) do accept `""` but I think being more lenient than the OS is not a major problem for these functions.  In contrast, users will likely use `pathIsDirectory` and `doesDirectoryExist` to validate paths, so being too lenient is more likely to be an issue.

I'm making some significant refactoring because of this, but the only user-facing change should be that `pathIsDirectory` and `doesDirectoryExist` will no longer accept empty paths, as they used to be.  In the code of `directory`, it will be more obvious which functions do accept empty paths (because they will call `emptyToCurdir`).  Due to various flaws in `normalise`, nearly all uses have been replaced with `System.Directory.Internal.Common.simplify` instead.
